create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  interest text not null,
  message text not null,
  source text not null default 'digital-presence-clinics-website'
);

alter table public.contact_requests enable row level security;

drop policy if exists "Allow public contact form inserts" on public.contact_requests;

create policy "Allow public contact form inserts"
on public.contact_requests
for insert
to anon
with check (
  length(trim(name)) > 0
  and length(trim(email)) > 0
  and position('@' in email) > 1
  and length(trim(interest)) > 0
  and length(trim(message)) > 0
);
